### ISSUE TITLE
Question:霊界での生存者ボイチャの視聴について

### ISSUE THREAD

**Issue by Lighthigh57** [TumoiYorozu/DiscordWerewolf.ts#28]
初めまして、質問失礼します。
僕は、このゲームでの霊界で、生存者のボイチャを聞きながら、霊界でがやをいれるように、
チャンネル内の音声を別のチャンネルに転送するBOTを探していました。
しかし、見つけたBOTは、マルチストリームに対応していなく、解決策を募集していたので、
自分もこのような機能を単体で実現してほしいこともあり、Questionという形で書かせていただきました。
[こちら](https://qiita.com/suzukey/items/87e075f43da2a714fe71)が、そのBOTです。
僕も、DiscordBotに関しては完全に初心者なので、お力になれない部分もありますが、
ぜひ、仕組みを教えていただけますでしょうか？
長文失礼しました。

**Comment by Lighthigh57** [comment]
※BOTは自分が作ったものではありません

**Comment by TumoiYorozu** [comment]
こんにちは。

端的に言うと、通話・BGMをそれぞれ wav ストリームで受け取って、それを以下の部分で自力で mix しています。
https://github.com/TumoiYorozu/DiscordWerewolf.ts/blob/master/src/LiveStream.ts

wav は基本的にそのまま足し算すれば音声が合成できるので、この方式でやっています。
JS は基本的に1スレッドしか使えないのも有り、正直結構処理のボトルネックにはなっていてもう少し効率的なライブラリに投げたい気持ちもあるのですが見つからず、まぁそこそこのスペックのPCならギリギリ耐えると言うことでとりあえずこうしています。

**Comment by Lighthigh57** [comment]
なるほど！返信ありがとうございます！
そのプログラムは何か参考サイトなどをもとに書かれたのですか？
それとも完全オリジナル（？）ですか？

**Comment by TumoiYorozu** [comment]
返信忘れててすみません、ほぼ大体オリジナルです

**Comment by jirno7pr** [comment]
@Lighthigh57 横から失礼します。
Lighthigh57さんが見つけたBOT([discord_transfer](https://github.com/suzukey/discord_transfer))のマルチストリームに対応していない問題点についてですが、
TumoiYorozuさんの実装を参考にさせて頂き、以下プルリクで問題解決しマルチストリーム対応しております。ご参考まで。
https://github.com/suzukey/discord_transfer/pull/3

**Comment by TumoiYorozu** [comment]
@[jirno7pr](https://github.com/jirno7pr) 素晴らしいです！　ちょうど音声転送だけ切り出した bot を作りたいと思っていました。
参考情報なのですが、人狼bot を d.js v13 に対応アプデしました。
https://github.com/TumoiYorozu/DiscordWerewolf.ts/commit/a288e422e6eb5c57841e6faaed5df668ab616884

しかし現在、 d.js v13 には音声周りのバグがあるため、ちょっと素直には行きません。
https://github.com/TumoiYorozu/DiscordWerewolf.ts/wiki/Discord.js-v13-%E3%81%A7%E3%80%81%E3%83%9C%E3%82%A4%E3%82%B9%E3%83%81%E3%83%A3%E3%83%83%E3%83%88%E3%81%AE%E9%9F%B3%E5%A3%B0%E8%BB%A2%E9%80%81%E3%81%8C%E3%81%86%E3%81%BE%E3%81%8F%E3%81%84%E3%81%8B%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88

v13 に対応するときは参考にしてください。


Tips:
GitHub では、コミットメッセージに細工すると co-authored コミットと呼ばれる、複数の作者を持つコミットが作れます。  
可能ならこの仕組みを使っていただけると、より嬉しいです～（強制ではないですし、判断に任せます）
https://docs.github.com/ja/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by shoshoi** [comment]
@TumoiYorozu jirno7prです。アカウントを移行したためこちらからメッセージします。
情報ありがとうございます！v13対応する際に参考にさせて頂きます。
co-authoredにつきましても承知しました。https://github.com/TumoiYorozu/DiscordWerewolf.ts/commit/a288e422e6eb5c57841e6faaed5df668ab616884 のアップデートを取り込む際にco-authoredを追加させて頂きます。
