### ISSUE TITLE
Question:ライセンスについて

### ISSUE THREAD

**Issue by jirno7pr** [TumoiYorozu/DiscordWerewolf.ts#30]
初めまして。ライセンスについてご質問させてください。
DiscordWerewolf.tsにライセンスは設定されていますでしょうか？
（DiscordWerewolf.tsを改造したBotを公開することは可能でしょうか？）
お手数ですがご確認お願いいたします。

**Comment by TumoiYorozu** [comment]
ライセンスは特に考えていないのですが、このリポジトリのURLとオリジナル作者「TumoiYorozu」を明記していれば、改造の公開は問題無いと考えています。

**Comment by TumoiYorozu** [comment]
（特にこの Question とは関係ないのですが、深刻なものではないけどいくつか挙動がバグってた気がしていて明日あたり直そうと思っていました）

**Comment by jirno7pr** [comment]
ご回答ありがとうございます。
`ライセンスは特に考えていないのですが、このリポジトリのURLとオリジナル作者「TumoiYorozu」を明記していれば、改造の公開は問題無いと考えています。`
上記承知しました。もし公開する場合は上記の通り明記させて頂きます。
